### ISSUE TITLE
Equity check as view?

### ISSUE THREAD

**Issue by dmklinger** [CityOfLosAngeles/mds-dev#11]
Equity check through stratified random sample is very easy to implement in PostGIS with Availability view. Is it worth it? Will there be performance gains relative to Python?

Also, I think equity check (over a given time frame) could be implemented in a better, but more difficult to implement way: we can find an accurate average for each area by integrated the function n(t)/T over the given time frame where n is the number of bikes, t is the time (variable), and T is the time difference we are interested in. I don't think this is feasible in PostGIS, but it is in Python, and will give a much more accurate count. It will also be time-agnostic, so we can look over a day, a week, a month, a year, whatever, and get an accurate answer for all of them. 

Thoughts?

**Comment by dmklinger** [comment]
Algorithm to do this: 
1) Choose start_time, end_time.
2) Find all trips that overlap with that interval
3) Order those trips by their start time
4) construct an interval [(start_time,end_time,0)] i.e. a list of tuples, each containing a start_time, end_time, and number of available bikes in that interval
5) iterate through all trips, each time updating our interval. So, for example, if a > start_time and b < end_time, and a bike is available at from a to b, we should update our empty interval to be [(start_time,a,0),(a,b,1),(b,end_time,0)]
6) After this is done (and all nasty edge cases dealt with), we will have constructed the function n(t). 
7) Go through each tuple (s,e,n) and calculate (e-s)*n. The sum of these is our integral.
8) Divide that sum by (end_time-start_time). This is the desired result.

**Comment by hunterowens** [comment]
@dmklinger I think we can close this?

**Comment by dmklinger** [comment]
yes

**Comment by dmklinger** [comment]
yes
