### ISSUE TITLE
Put create tables into a separate file

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mds-dev#4]
Let's put the create tables into a separate file with the `.sql` extension rather than inside of the `.py` files.

**Comment by dmklinger** [comment]
fill_tables.py makes more sense as a python script. sql isn't exactly made to parse jsons. in any case, it has the least ridiculous python->sql code: it just uses df.to_sql() from pandas

**Comment by hunterowens** [comment]
closing.
