### ISSUE TITLE
Add views to create_table file

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mds-dev#5]
We should create the following views 

* Availability View 
* Route Geometry View - using  [PostGIS Geometry/Line Type](http://www.postgis.net/docs/ST_MakeLine.html)

**Comment by dmklinger** [comment]
what do you mean by availability view?

**Comment by hunterowens** [comment]
Since we merged the status_change from avaliability, let's create a table
that has a start_on_street_time, end_on_street_time and placement/leaving
reasons.

**Comment by dmklinger** [comment]
Ah, I see - this will take some work.
