### ISSUE TITLE
Suggestion for server representation: seperate rows for each route entry

### ISSUE THREAD

**Issue by dmklinger** [CityOfLosAngeles/mds-dev#8]
After a lot of thought of how the data is represented/various ways of implementing postgis, I think one way we could parse the file is to write a different row for each recorded location and timestamp. This will allow for a lot more flexibility in creating route views. 

Thoughts?

**Comment by hunterowens** [comment]
I think this is interesting.

My gut instinct would be to follow the ELT pattern rather than ETL, and
load the JSON into the trips table and then create a routes table using a
trigger that unfurls the JSON. @bryanblackford might have more ideas.

**Comment by dmklinger** [comment]
This is implemented in route_geometry. Route_geometry will parse geojson and gives each point in route its own record with location and timestamp.
